### ISSUE TITLE
Move into scijs organization

### ISSUE THREAD

**Issue by rreusser** [jalava/ndarray-blas-dger#2]
I need to stop and think a moment about the process (as simple as you transferring ownership?) but is it alright with you if we merge this into the scijs organization? Any and all contributions are greatly appreciated!

**Comment by jalava** [comment]
I'm more than happy to transfer this and npm to scijs, as I just
implemented what I happened to need at the moment :)

I just need to figure out details on how to do it on npm as you can just
fork this repo and then modify package.json to point to new repo and
publish as soon as it's transferred.

**Comment by jalava** [comment]
I added you to npm owners list, so you can move this package under scijs if wanted.

**Comment by rreusser** [comment]
Great! Yeah, npm management is a little weird at the moment, but as long as there's some redundancy we should be good.

Followup: can you go to https://github.com/jalava/ndarray-blas-dger/settings and transfer ownership to `scijs` (the scijs organization)? Attribution won't change but this makes it a little easier to locate and maintain under the scijs index ( https://github.com/scijs ). Thanks so much!

**Comment by jalava** [comment]
You should make just a fork and then transfer that fork to scijs yourself
as otherwise I need admin rights to scijs.

**Comment by rreusser** [comment]
Gotcha. Thanks. Haven't been on the receiving end of many repo transfers. Still ironing out/establishing practices for this stuff. Input/critique is welcome! I'm back from vacation and hard at work on this stuff, so if you're interested in contributing more or helping steer things, any and all input is welcome!
